<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Preload_KB_Redis</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>646d038a-7ea8-4270-8b7a-66e4a5ece814</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
    <PackageReference Include="Microsoft.Azure.StackExchangeRedis" Version="3.2.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.6" />
    <PackageReference Include="Redis.OM" Version="1.1.0" />
    <PackageReference Include="Redis.OM.Vectorizers" Version="1.1.0" />
  </ItemGroup>

</Project>
